# Generated by Django 3.1.6 on 2021-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=300, verbose_name='image_name')),
                ('image_before_resize', models.CharField(max_length=300, verbose_name='image_before_resize')),
                ('image_after_resize', models.CharField(max_length=300, verbose_name='image_after_resize')),
                ('add_time', models.DateTimeField(verbose_name='add time')),
            ],
        ),
    ]
