# Generated by Django 3.1.6 on 2021-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=300, verbose_name='image_name')),
                ('image_path', models.CharField(max_length=300, verbose_name='image_path')),
                ('add_time', models.DateTimeField(verbose_name='add time')),
            ],
        ),
    ]
