# Generated by Django 3.1.6 on 2021-02-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageStorage',
        ),
    ]
